### ISSUE TITLE
custom options

### ISSUE THREAD

**Issue by romanoffs** [wollio/angular2_photoswipe#15]
Hi, how can I add my own settings, for example background transparency?

**Comment by SEVCO** [comment]
I'll provide ;)

**Comment by SEVCO** [comment]
https://github.com/wollio/angular2_photoswipe/pull/17

**Comment by romanoffs** [comment]
Thanks)

**Comment by romanoffs** [comment]
Thanks)

**Comment by SEVCO** [comment]
Need some time to implement Function Adapters
