### ISSUE TITLE
Add custom Button on Lightbox

### ISSUE THREAD

**Issue by javanese84** [wollio/angular2_photoswipe#25]
Is there a way to add a custom button with function call to the Lightbox Overlay?

**Comment by pmc-sstaehle** [comment]
Are there any plans top support this feature in the near future?

**Comment by SEVCO** [comment]
Its already implemented but it isn't released yet

**Comment by SEVCO** [comment]
Explain please what kind of button and where ?

**Comment by wollio** [comment]
solved with 8.0.0 release
