### ISSUE TITLE
Getting error setting up photoswipe

### ISSUE THREAD

**Issue by labago** [wollio/angular2_photoswipe#29]
![image](https://user-images.githubusercontent.com/1053978/68796307-a084cf80-0620-11ea-835d-50379946693c.png)

The generic type error, the second error isn't a problem. Any ideas?

**Comment by SEVCO** [comment]
Hello

Could you please provide more information (angular version, angular2photoswipe version)

**Comment by labago** [comment]
{
  "name": "ng-x-rocket",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "ng": "ng",
    "build": "npm run env -s && ng build --prod",
    "build:dev": "npm run env -s && ng build --output-path=caaacademy.mogadigitalstaging.com",
    "start": "npm run env -s && ng serve --aot --aot --proxy-config proxy.conf.js",
    "serve:sw": "npm run build -s && npx http-server ./dist -p 4200",
    "lint": "ng lint && stylelint \"src/**/*.scss\" --syntax scss && htmlhint \"src\" --config .htmlhintrc",
    "test": "npm run env -s && ng test",
    "test:ci": "npm run env -s && npm run lint -s && ng test --code-coverage --watch=false",
    "e2e": "npm run env -s && ng e2e",
    "translations:extract": "ngx-translate-extract --input ./src --output ./src/translations/template.json --format=json --clean --sort --marker extract",
    "docs": "hads ./docs -o",
    "env": "ngx-scripts env npm_package_version",
    "prettier": "prettier --write \"./{src,e2e}/**/*.{ts,js,html,scss}\"",
    "prettier:check": "prettier --list-different \"./{src,e2e}/**/*.{ts,js,html,scss}\"",
    "postinstall": "npm run prettier -s",
    "generate": "ng generate"
  },
  "dependencies": {
    "@angular/animations": "^7.2.3",
    "@angular/common": "^7.2.3",
    "@angular/compiler": "^7.2.3",
    "@angular/core": "^7.2.3",
    "@angular/forms": "^7.2.3",
    "@angular/http": "^7.2.3",
    "@angular/platform-browser": "^7.2.3",
    "@angular/platform-browser-dynamic": "^7.2.3",
    "@angular/router": "^7.2.3",
    "@angular/service-worker": "^7.2.3",
    "@contentful/rich-text-html-renderer": "^13.4.0",
    "@fnxone/ngx-photoswipe": "^1.0.4",
    "@fortawesome/fontawesome-free-webfonts": "^1.0.9",
    "@ng-bootstrap/ng-bootstrap": "^4.0.4",
    "@ngx-translate/core": "^11.0.1",
    "@types/photoswipe": "^4.0.29",
    "angular2_photoswipe": "^8.0.1",
    "bootstrap": "^4.1.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.7",
    "hammerjs": "^2.0.8",
    "imagesloaded": "^4.1.4",
    "morgan": "^1.9.1",
    "ng-sidebar": "^8.0.0",
    "ng2-countdown-timer": "^1.2.2",
    "ngx-lightbox": "^1.2.0",
    "photoswipe": "^4.1.3",
    "rxjs": "^6.5.1",
    "showdown": "^1.9.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.9.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.0",
    "@angular/cli": "~7.3.0",
    "@angular/compiler-cli": "^7.2.3",
    "@angular/language-service": "^7.2.3",
    "@biesbjerg/ngx-translate-extract": "^2.3.4",
    "@ngx-rocket/scripts": "^3.0.0",
    "@types/jasmine": "^3.3.8",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^8.10.13",
    "@types/showdown": "^1.9.2",
    "codelyzer": "^5.0.0",
    "hads": "^1.7.0",
    "htmlhint": "^0.11.0",
    "https-proxy-agent": "^2.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.2",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-junit-reporter": "^1.2.0",
    "prettier": "^1.16.3",
    "pretty-quick": "^1.10.0",
    "protractor": "~5.4.0",
    "puppeteer": "^1.12.0",
    "stylelint": "~10.0.1",
    "stylelint-config-prettier": "^5.1.0",
    "stylelint-config-recommended-scss": "~3.3.0",
    "stylelint-config-standard": "~18.3.0",
    "stylelint-scss": "~3.6.0",
    "ts-node": "~8.1.0",
    "tslint": "~5.16.0",
    "tslint-config-prettier": "^1.14.0",
    "typescript": "~3.2.0"
  },
  "prettier": {
    "singleQuote": true,
    "overrides": [
      {
        "files": "*.scss",
        "options": {
          "singleQuote": false
        }
      }
    ]
  }
}

**Comment by SEVCO** [comment]
try angular angular2photoswipe 7.1.0

**Comment by labago** [comment]
Thank you! That worked

**Comment by SEVCO** [comment]
Version 8 is built with angular 8 . I think they did a breaking change on @ViewChild. So you need to upgrade your angular version

**Comment by SEVCO** [comment]
Version 8 is built with angular 8 . I think they did a breaking change on @ViewChild. So you need to upgrade your angular version
