### ISSUE TITLE
Angular 6 Production Mode failing

### ISSUE THREAD

**Issue by Carlos95** [wollio/angular2_photoswipe#3]
Hi,

I am using angular2_photoswipe in an angular 6 webpage and when ran with --prod enabled, it gives the following error:

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'Angular2PhotoswipeModule' was called.

Any idea why this can be happening? 

KR

**Comment by wollio** [comment]
Hi

Sorry for my late reply. I just updated the demo app to angular6 and it seems to work. Do you still have a problem and can you provide a demonstration project?
I am now currently updating the whole package.

Kind regards

**Comment by wollio** [comment]
@Carlos95 Hi Carlos

Any news about the problem? If you don't feel like to test it, it's okay. But I'll close this issue now, because on my Angular 6 cli generated setup it is working.
If the error should persist, please open a new issue :-)

Kind regards

David
