### ISSUE TITLE
release 10.0.0

### ISSUE THREAD

**Issue by maiermic** [wollio/angular2_photoswipe#42]
NPM lists [10.0.0](https://www.npmjs.com/package/angular2_photoswipe/v/10.0.0) as latest version, but the repository lists [8.0.1](https://github.com/wollio/angular2_photoswipe/releases/tag/8.0.1) as latest version. Have you forgotten to list the version? What about version 9.0.0? Has it been skipped?

Thanks for your work 😊

**Comment by wollio** [comment]
Hi Michael,

Yes, it was not listed for any reasons. I'll look into it. Version 9 was skipped. Are any problems with version 10 or can I close the issue?

**Comment by maiermic** [comment]
Looks good so far :+1:
