### ISSUE TITLE
Support Angular 11-16

### ISSUE THREAD

**Issue by maiermic** [wollio/angular2_photoswipe#79]
`angular2_photoswipe` seems to work fine with higher Angular versions (at least 14) than specified (10). Upgrade dependencies to support Angular 11-16 explicitly. Otherwise, `npm install --force` has to be used to install `angular2_photoswipe` in higher Angular versions, which should be avoided.

**Comment by maiermic** [comment]
`angular2_photoswipe` is not compatible with Angular Ivy. Hence, it is not compatible with Angular 16.

**Comment by maiermic** [comment]
@wollio Thanks for creating `angular2_photoswipe`. I'm sure you're busy, as any good developer would be. Therefore, I would be happy to help with the maintenance as long as there is a chance that my PR will be merged. Would you review a PR and release a new version if I migrate the project to Angular 16?

**Comment by wollio** [comment]
Hi @maiermic 

Of course a PR is warmly welcomed. Unfortunately, I personally do not use the library anymore and therefore have no interest in developing it further. But I would definitely merge a PR

**Comment by maiermic** [comment]
@wollio Kindly reminder that I'm waiting for the PR to be reviewed/merged/released 😉

**Comment by wollio** [comment]
@maiermic version 16.2.1 has been released :)

**Comment by maiermic** [comment]
@wollio Thank you very much :heart:
